expense/urls.py
from django.urls import path
from . import views

urlpatterns=[
    path('', views.home, name = "home"),
    path("ExpenseList",views.expenseList, name="expenselist"),
    path("CreateExpense",views.handleExpense, name="createExpense"),
    path('editExpense/<int:id>', views.editExpense, name='editExpense'),
    path('updateExpense/<int:id>',views.updateExpense,name = 'update'),
    path('deletExpense/<int:id>',views.destroy,name='destroy'),
    path('loginExpense',views.loginExpense, name='login'),
   

  
]

finance_pro/urls.py
from django.contrib import admin
from django.urls import path,include

from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    path('admin/', admin.site.urls),
    path('',include('expense.urls')),
]

if  settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL,document_root=settings.MEDIA_ROOT)

expense/models.py
from django.db import models
from django.contrib.auth.models import AbstractUser,User,Group

import datetime
import os
from django.conf import settings




class Expense (models.Model):
    name = models.CharField(max_length=150,null=False,blank=False)
    date = models.DateField()
    category = models.CharField(max_length=50, choices=[('Health', 'Health'), ('Electronics', 'Electronics'), ('Travel', 'Travel'), ('Education', 'Education'), ('Books', 'Books'), ('Others', 'Others')])
    description = models.TextField()
    amount = models.PositiveIntegerField()
    created_by = models.ForeignKey(settings.AUTH_USER_MODEL, on_delete=models.CASCADE)
    created_at = models.DateTimeField(auto_now_add=True)
    updated_at = models.DateTimeField(auto_now=True)

    """def save(self, *args, **kwargs):
        if not self.created_by:
            self.created_by = kwargs.pop('user', None)
        super(Expense, self).save(*args, **kwargs)"""

    def __str__(self):
        return self.name    

Group.objects.get_or_create(name='ExpenseCreator')  # Users who can create expenses
Group.objects.get_or_create(name='ExpenseAdmin')

expense/forms.py
# forms.py
from django import forms
from .models import Expense

class ExpenseForm(forms.ModelForm):
    class Meta:
        model = Expense
        fields = ['name', 'category', 'date', 'amount']
    
    category = forms.CharField(required=False)
    date = forms.DateField(required=False)
    amount = forms.DecimalField(required=False)

expense/views.py
from django.shortcuts import render,redirect,get_object_or_404
from django.contrib.auth import authenticate, login
from . forms import *
from django.contrib.auth.decorators import login_required
from .models import *
from datetime import datetime
from django.db.models import Q
from django.contrib.auth.decorators import user_passes_test

from django.contrib import messages
from django.contrib.auth.forms import AuthenticationForm
# Create your views here.
def home(request):
    return render(request, 'index.html')
"""
def expenseList(request):
    Exp= Expense.objects.filter(created_by=request.user)
    return render(request, 'expenseList.html',{"Expense":Exp})
"""
def is_expense_creator_or_superuser(user):
    return user.is_superuser or user.groups.filter(name='ExpenseCreator').exists()

@user_passes_test(is_expense_creator_or_superuser, login_url='/loginExpense')
def expenseList(request):

    if request.method == 'POST' and 'logout' in request.POST:
        logout(request)
        return redirect('loginExpense')  # Replace 'your_login_url' with the actual URL pattern name for your login view
        
    date_filter = request.GET.get('date_filter')
    expense_name_filter = request.GET.get('expense_name_filter')

    expenses = Expense.objects.filter(created_by=request.user)

    if date_filter:
        try:
            date_filter = datetime.strptime(date_filter, '%Y-%m-%d').date()
            expenses = expenses.filter(date=date_filter)
        except ValueError:
            # Handle invalid date format if needed
            pass

    if expense_name_filter:
        expenses = expenses.filter(name__icontains=expense_name_filter)

   

    return render(request, 'expenseList.html', {"Expense": expenses, "is_creator": True})




def handleExpense(request):
    if request.method == "POST":
        form = ExpenseForm(request.POST)
        if form.is_valid():
            # Save the form data to the database
            expense = form.save(commit=False)
            expense.created_by = request.user  # Assuming you have user authentication
            expense.save()
            messages.success(request, 'Expense added successfully!')
            return redirect('expenselist')  # Redirect to the expense list page after successful form submission
        else:
            messages.error(request, 'Expense creation failed. Please check the form.')
    
    else:
        form = ExpenseForm()

    return render(request, 'createExpense.html', {'form': form})

def editExpense(request,id):
    expense = Expense.objects.get(id=id)
    return render(request,'editExpense.html',{'expense': expense})

def updateExpense(request, id):
    if request.method == "POST":
        expense = Expense.objects.get(id=id)
        form = ExpenseForm(request.POST, instance=expense)
        if form.is_valid():
            form.save()
            messages.success(request, 'Expense updated successfully!')
            return redirect('expenselist')  # Redirect to your expense list or home page
        else:
            messages.error(request, 'Expense update failed. Please check the form.')
        print(form.errors)

    return render(request,"editExpense.html",{"expense": expense}) 

def destroy (request, id):
    """expense = Expense.objects.get(id=id)
    expense.delete()
    messages.warning(request, 'Expense deleted successfully!')
    return redirect('expenselist')"""
    expense = get_object_or_404(Expense, id=id)

    if request.method == 'POST':
        expense.delete()
        messages.warning(request, 'Expense deleted successfully!')
        return redirect('expenselist')

    return render(request, 'confirm_delete.html', {'expense': expense})

def loginExpense (request):
    if request.method == 'POST':
        form = AuthenticationForm(request, data=request.POST)
        if form.is_valid():
            username = form.cleaned_data.get('username')
            password = form.cleaned_data.get('password')
            user = authenticate(request, username=username, password=password)

            if user is not None:
                login(request, user)
                messages.success(request, f'Welcome, {username}!')
                return redirect('expenselist')  # Replace with your desired redirect URL
            
        
    else:
        form = AuthenticationForm()

    return render(request, 'login.html', {'form': form})


    

expense/templates/confirm_delete.html
{% extends 'layouts/main.html' %}

{% block content %}
<div class="container mt-4">
    <div class="card">
        <div class="card-body">
            <div class="row">
                <h5 class="col-12 text-center fs-3 fw-bold">
                    Confirm Deletion
                </h5>
            </div>
            <div class="row">
                <div class="col-12 text-center">
                    <p class="card-text ">Are you sure you want to delete this expense?</p>
                </div>
            </div>           
            
            <div class="row">
                <div class="col-6 text-center">
                    <form method="post">
                        {% csrf_token %}
                        <button type="submit" class="btn btn-danger">Yes</button>
                    </form>
                </div>
                <div class="col-6 text-center">
                    <a href="{% url 'expenselist' %}" class="btn btn-secondary">No</a>
                </div>
                    
               


            </div>
            
        </div>
    </div>
</div>
{% endblock content %}

expense/templates/createExpense.html
{% extends 'layouts/main.html' %}

{% block content %}
{% if messages %}
    <ul class="messages">
        {% for message in messages %}
            <li{% if message.tags %} class="{{ message.tags }}"{% endif %}>{{ message }}</li>
        {% endfor %}
    </ul>
{% endif %}

<form method="post" action="CreateExpense" class="form-control">
    {% csrf_token %}
    <div class="container">
        {% csrf_token %}
        <div class="container">
            <div class="col-12">
                <h3>Edit Expense</h3>
            </div>
            <div class="mb-3">
                <label>Name </label>
                <input type="text" class="form-control" name="name" id="id_name" >            </div>
            <div class="mb-3">
                <label>Description</label>
                <input type="text" class="form-control" name="description" id="id_description" >
            </div>
            <div class="mb-3">
                    <label>Category : Books | Electronics | Education | Health | Travel | Others</label>
                <input type="text" class="form-control" name="category" id="id_category" >

                
            </div>
            <div class="mb-3">
                <label>Date of Expense</label>
                <input type="date" class="form-control" name="date" id="id_date" >            </div>
            <div class="mb-3">
                <label>Expense Amount</label>
                <input type="number" class="form-control" name="amount" id="id_amount" >
            </div>
        <button type="submit" cl>Create Expense</button>
    </div>
    
</form>





<!--
<form method="POST" action="CreateExpense">
    {% csrf_token}
    <label>Name</label>
    <input type="text" name="name">
    <label>Description</label>
    <input type="text" name="Description">

    <label>Category</label>
    <input type="radio" name="category" value="Health" >
    <input type="radio" name="category" value="Electronics">
    <input type="radio" name="category" value="Travel">
    <input type="radio" name="category" value="Education">
    <input type="radio" name="category" value="Books">
    <input type="radio" name="category" value="Others">
    <label>Date of Expense</label>
    <input type="datetime-local" name="date">
    <label>Expense Amount</label>
    <input type="number" name="amount">-->


</form>

    
{% endblock content %}

expense/templates/dateFilter.html
{% extends 'layouts/main.html' %}

{% block content %}
<form method="get" action="dated">
    <input type="date" name="date_filter" />
    <button type="submit">Filter by Date</button>
</form>
{% endblock content %}

expense/templates/deleteExpense.html
{% extends 'layouts/main.html' %}

{% block content %}

    
{% endblock content %}

expense/templates/editExpense.html
{% extends 'layouts/main.html' %}

{% block content %}
<!--


<div class="col-md-12">
    <form method="POST" class="post-form" action="editExpense">
    {% csrf_token %}
    <div class="container">
        <div class="col-12">
            <h3>Edit Expense</h3>
        </div>
        <div class="mb-3">
            <label>Name </label>
            <input type="text" class="form-control" name="name" id="id_name" value="{{Expense.name}}">

        </div>
        <div class="mb-3">
            <label>Description</label>
            <input type="text" class="form-control" name="description" id="id_description" value="{{expense.description}}">

        </div>
        <div class="mb-3">

            <label>Category</label>
            <input type="radio" class="form-control" name="name" id="id_category" value= "Expense.category">

        </div>
        <div class="mb-3">

        <label>Date of Expense</label>
        <input type="datetime-local" class="form-control" name="name" id="id_date" value="{{Expense.date}}">

        </div>
        <div class="mb-3">
            <label>Expense Amount</label>
            <input type="number" class="form-control" name="name" id="id_id" value="{{expense.amount}}">

        </div>
        <div class="mb-3">
            <button type="submit">Save Changes</button>
        </div>
    
    </div>
    
    
    </form>
</div>
-->
<div class="col-md-12">
    <form method="POST" class="post-form" action="{% url 'update' id=expense.id %}">
        {% csrf_token %}
        <div class="container">
            <div class="col-12">
                <h3>Edit Expense</h3>
            </div>
            <div class="mb-3">
                <label>Name </label>
                <input type="text" class="form-control" name="name" id="id_name" value="{{ expense.name }}">
            </div>
            <div class="mb-3">
                <label>Description</label>
                <input type="text" class="form-control" name="description" id="id_description" value="{{ expense.description }}">
            </div>
            <div class="mb-3">
                <label>Category : Books | Electronics | Education | Health | Travel | Others</label>
                <input type="text" class="form-control" name="category" id="id_category" value="{{ expense.category }}">
            </div>
            <div class="mb-3">
                <label>Date of Expense</label>
                <input type="date" class="form-control" name="date" id="id_date" value="{{ expense.date }}">
            </div>
            <div class="mb-3">
                <label>Expense Amount</label>
                <input type="number" class="form-control" name="amount" id="id_amount" value="{{ expense.amount }}">
            </div>
            
            <div class="mb-3">
                <button class ="btn-outline-success" type="submit">Save Changes</button>
            </div>
        </div>
    </form>
</div>

    
{% endblock content %}

expense/templates/expenseList.html
{% extends 'layouts/main.html' %}
{% block content %}
{% if messages %}
    <ul class="messages">
        {% for message in messages %}
            <li{% if message.tags %} class="{{ message.tags }}"{% endif %}>{{ message }}</li>
        {% endfor %}
    </ul>
{% endif %}

<nav class="navbar navbar-expand-lg navbar-light bg-light">
    <div class="container-fluid">
        <a class="navbar-brand">My Expense Manager</a>
        <form class="d-flex mx-2" action="{% url 'home' %}" method="post">
            {% csrf_token %}
            <button class="btn btn-outline-danger" type="submit">Logout</button>
          </form>

        <form class="d-flex mx-2" >
            <div class="input-group">
                <input type="date" class="form-control" name="date_filter" />
                <button class="btn btn-outline-success" type="submit">Filter by Date</button>
            </div>
        </form>

        <form class="d-flex mx-2">
            <div class="input-group">
                <input type="text" class="form-control" name="expense_name_filter" placeholder="Search by Expense Name" />
                <button class="btn btn-outline-success" type="submit">Search</button>
            </div>
        </form>

        <!-- Add styling to your "New Expense" button -->
        <a class="btn btn-outline-success" href="CreateExpense">New Expense</a>
    </div>
</nav>

  <table class="table">
    <thead class="table-light">
        <tr>
            <th scope="col"> Name</th>
            <th scope="col"> Category</th>
            <th scope="col"> Date of Expense</th>
            <th scope="col"> Amount</th>
            <th scope="col"> Updated At</th>
            <th scope="col"> Created by</th>
            
            {% if user.is_authenticated %}
            <th scope="col">#</th>
            {% endif %}
        </tr>
    </thead>
    <tbody>
        {% for item in Expense %}
        <tr>
            <td>{{ item.name }}</td>
            <td>{{ item.category }}</td>
            <td>{{ item.date }}</td>
            <td>INR {{ item.amount }}</td>
            <td>{{ item.updated_at }}</td>
            <td>{{ item.created_by }}</td>
            {% if user.is_authenticated %}
                {% if user == item.created_by %}
                    <td>

                        <a href="editExpense/{{item.id}}" style="padding-right: 15px;">
                        <i class="fas fa-edit"></i> 
                        </a>
                        <a type="button"   href="deletExpense/{{item.id}}">
                        <i class="fas fa-trash-alt"></i>
                        </a> 
                              
                    </td>
                {% else %}
                    <td></td>
                {% endif %}
            {% else %}
                <td></td>
            {% endif %}       

        </tr>
        {% endfor %}
    </tbody>
  </table>
  <script>
    function confirmDelete(expenseId) {
        var result = confirm("Are you sure you want to delete this expense?");
        if (result) {
            window.location.href = "/destroy/" + expenseId + "/";
        }
    }
</script>



{% endblock content %}

expense/templates/index.html
{% extends 'layouts/main.html' %}

{% block content %}


<div class="container login-container">
    <h2 class="text-center mb-4">Login</h2>
    <form method="post" class="form-control" action="loginExpense">
        {% csrf_token %}
        <div class="mb-3">
            <label for="username" class="form-label">Username</label>
            <input type="text" class="form-control" id="username" name="username" required>
        </div>
        <div class="mb-3">
            <label for="password" class="form-label">Password</label>
            <input type="password" class="form-control" id="password" name="password" required>
        </div>
        <button type="submit" class="btn btn-primary">Login</button>
    </form>
</div>

{% endblock content %}

expense/templates/layouts/main.html
{% load static %}
<!doctype html>
<html lang="en">

  <head>
    <!-- Required meta tags -->
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1">
   
    <!-- Bootstrap CSS -->
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.0.2/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-EVSTQN3/azprG1Anm3QDgpJLIm9Nao0Yz1ztcQTwFspd3yD65VohhpuuCOmLASjC" crossorigin="anonymous">

    <title>Finance Management</title>
    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/6.5.1/css/all.css" integrity="sha512-tx5+1LWHez1QiaXlAyDwzdBTfDjX07GMapQoFTS74wkcPMsI3So0KYmFe6EHZjI8+eSG0ljBlAQc3PQ5BTaZtQ==" crossorigin="anonymous" referrerpolicy="no-referrer" />
  </head>
  <body>
    
    {% block content %}
    {% endblock content %}

    {% block scripts %}
    {% endblock scripts %}
 
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.0.2/dist/js/bootstrap.bundle.min.js" integrity="sha384-MrcW6ZMFYlzcLA8Nl+NtUVF0sA7MsXsP1UyJoMp4YLEuNSfAP+JcXn/tWtIaxVXM" crossorigin="anonymous"></script>

    
  </body>
</html>